ckjhsLibraryWEB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import login, logout
  # 利用內建的view funciton
from main import views
urlpatterns = [
	path('book/', include('main.urls')),
    path('admin/', admin.site.urls),
	path('login/', views.loginview, name='loginview'),
	path('logout/', views.logoutview, name='logoutview'),
	path('register/', views.registerview, name='registerview'),
	path('newbook/', views.addBookView, name='addBookView'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:books_id>/', views.detail, name='detail'),
	path('rent/', views.rent, name='rent'),
	path('rent/confirm/', views.rent_confirm, name='confirm'),
	path('history/', views.history, name='history')
	# path('rent/', views.rent(), name='rent')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Books(models.Model):
    book_title = models.CharField(blank=True, null=True, max_length=200)
    book_author = models.CharField(blank=True, null=True, max_length=200)
    book_pubtime = models.CharField(blank=True, null=True, max_length=20)
    book_isbn = models.CharField(blank=True, null=True, max_length=13)
    book_borrowid = models.CharField(blank=True, default='', max_length=5)
    book_borrowname = models.CharField(blank=True, default='', max_length=5)
    book_barcode = models.CharField(blank=True, default='', max_length=5)

    def __str__(self):
        return self.book_title


class NewBooks(models.Model):
    book_title = models.CharField(blank=True, default='', max_length=200)
    book_author = models.CharField(blank=True, default='', max_length=200)
    book_pubtime = models.CharField(blank=True, default='', max_length=20)
    book_isbn = models.CharField(blank=True, default='', max_length=13)
    book_borrowid = models.CharField(blank=True, default='', max_length=5)
    book_borrowname = models.CharField(blank=True, default='', max_length=5)
    book_barcode = models.CharField(blank=True, default='', max_length=5)

    def __str__(self):
        return self.book_title


class Borrows(models.Model):
    borrower = models.CharField(max_length=100)
    rent_time = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100, default='')
    isbn = models.CharField(max_length=100)
    barcode = models.CharField(max_length=10, default='')
    pubtime = models.CharField(max_length=100, default='')
    return_time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.borrower


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    real_name = models.CharField(max_length=5)
    school_id = models.CharField(max_length=5)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class BookForm(forms.Form):
    book_barcode = forms.CharField(label='書籍條碼(例如:A1001)', max_length=100)


class LoginForm(forms.Form):
    username = forms.CharField(label='帳號', max_length=50)
    password = forms.CharField(label='密碼', max_length=50, widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    real_name = forms.CharField(help_text='請輸入真實姓名', max_length=5)
    school_id = forms.CharField(help_text='例如：41402', max_length=5)

    class Meta:
        model = User
        fields = ('username', 'real_name', 'school_id', 'password1', 'password2')


class AddBookForm(forms.Form):
    isbn = forms.CharField(label='書籍ISBN', max_length=100)
    barcode = forms.CharField(label='書籍條碼', max_length=5)
    title = forms.CharField(label='標題')
    author = forms.CharField(label='作者')
    pubtime = forms.CharField(label='出版日期')

main/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .models import Books, NewBooks, Borrows
from .forms import BookForm, LoginForm, RegisterForm, AddBookForm
from .rent import confirm_rent_database
book_list = []
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'all_book_list'  # the list name of book list in html

    def get_queryset(self):
        """Return all books in datebase"""
        return NewBooks.objects.all()

# def check_admin:
#    return user.is_superuser


@login_required(login_url='/login/')
def rent(request):
    global book_list
    message = ''
    error = False
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            barcode = form.cleaned_data['book_barcode']
            form = BookForm()
            try:
                book = NewBooks.objects.get(book_barcode=barcode)
                print(book.book_borrowid)
                if book in book_list:
                    message = '請勿重複掃描書籍'
                    messages.warning(request, message, extra_tags='alert')
                    return render(request, 'main/rent.html', {'form': form, 'book_list': book_list})
                if book.book_borrowid != request.user.profile.school_id and not book.book_borrowid == '':
                    message = '這本書已被{} {}借出, 請選擇其他書籍'.format(
                        book.book_borrowid, book.book_borrowname)
                    messages.warning(request, message, extra_tags='alert')
                else:
                    book_list.append(book)
            except:
                message = '請刷入有效的條碼'
                messages.warning(request, message, extra_tags='alert')
    else:
        form = BookForm()
    return render(request, 'main/rent.html', {'form': form, 'book_list': book_list})


@login_required(login_url='/login/')
def rent_confirm(request):
    global book_list
    if len(book_list) == 0:
        messages.error(request, '請先借閱書籍', extra_tags='alert')
        return render(request, 'main/rent_confirm.html')
    borrow_list = list(book_list)
    book_list = []
    print(request.user.username)
    confirm_rent_database(borrow_list, request.user)
    messages.success(request, '借閱&歸還成功', extra_tags='alert')
    return render(request, 'main/rent_confirm.html', {'borrow_list': borrow_list})


@login_required(login_url='/login/')
def history(request):
    borrow_list = Borrows.objects.filter(borrower=request.user.profile.real_name)
    return render(request, 'main/history.html', {'borrow_list': borrow_list})


def detail(request, books_id):
    book = get_object_or_404(NewBooks, pk=books_id)  # use book_id as a url
    return render(request, 'main/detail.html', {'book': book})  # return a dict contain book's date


def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/book/')
        else:
            form = LoginForm()
            message = '找不到帳號或帳號密碼錯誤'
            messages.error(request, message, extra_tags='alert')
    else:
        form = LoginForm()
    return render(request, 'main/login.html', {'form': form})


def logoutview(request):
    global book_list
    book_list = []
    logout(request)
    return HttpResponseRedirect('/book/')


def registerview(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.real_name = form.cleaned_data.get('real_name')
            user.profile.school_id = form.cleaned_data.get('school_id')
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/book/')
    else:
        form = RegisterForm()
    return render(request, 'main/register.html', {'form': form})


def addBookView(request):
    if request.user.is_superuser:
        book_need_confirm = {}
        barcode = ''
        isbn = ''
        if request.method == 'POST':
            form = AddBookForm(request.POST)
            isbn = request.POST['isbn']
            barcode = request.POST['barcode']
            title = request.POST['title']
            author = request.POST['author']
            pubtime = request.POST['pubtime']
            print(request.POST)
            if 'search' in request.POST:
                try:
                    book_need_confirm = Books.objects.get(book_isbn=isbn)
                except:
                    message = '資料庫中無此書籍'
                    messages.warning(request, message, extra_tags='alert')
            elif form.is_valid() and 'save' in request.POST:
                try:
                    book = NewBooks.objects.get(book_barcode=barcode)
                    book.book_title = title
                    book.book_author = author
                    book.book_pubtime = pubtime
                    book.book_isbn = isbn
                    book.book_barcode = barcode
                    book.save()
                    barcode = ''
                    isbn = ''
                    message = '已儲存'
                    messages.success(request, message, extra_tags='alert')
                except:
                    book = NewBooks.objects.create()
                    book.book_title = title
                    book.book_author = author
                    book.book_pubtime = pubtime
                    book.book_isbn = isbn
                    book.book_barcode = barcode
                    book.save()
                    barcode = ''
                    isbn = ''
                    message = '已儲存'
                    messages.success(request, message, extra_tags='alert')

                form = AddBookForm()
        else:
            form = AddBookForm()

        return render(request, 'main/addbook.html', {'form': form, 'book_need_confirm': book_need_confirm, 'barcode': barcode, 'isbn': isbn})
    else:
        return HttpResponse('您沒有權限進入此頁面')

main/templates/main/addbook.html
{% extends 'main/base.html'%}
{% block content %}

{% if messages %}
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
	</div>
{% endfor %}
{% endif %}

<form method="post">
	{% csrf_token %}
	<p>
		<label for="book_username">ISBN：</label><br>
			<input type="text" id="isbn" name="isbn" value="{{ isbn}}" maxlength="150" />
	</p>
	<p>
		<label for="book_barcode">條碼：</label><br>
			<input type="text" name="barcode" value="{{ barcode }}" required maxlength="150" />
	</p>
	<p>
		<label for="book_title">標題：</label><br>
		<input type="text" name="title" value="{{ book_need_confirm.book_title}}" maxlength="150" />
	</p>
	<p>
		<label for="book_author">作者：</label><br>
			<input type="text" name="author" value="{{ book_need_confirm.book_author}}" maxlength="150" />
	</p>
	<p>
		<label for="book_pubtime">出版日期(例:2003-8)：</label><br>
			<input type="text" name="pubtime" value="{{ book_need_confirm.book_pubtime}}" maxlength="150" />
	</p>

	<input type="submit" value='查詢' name="search" class="btn btn-primary" />
	<input type="submit" value='儲存' name="save" class="btn btn-primary" />
</form>
<script>
	var input = document.getElementById("isbn");
	input.focus();
</script>
{% endblock content %}

main/templates/main/base.html
<html>
<head>
	<title>圖書管理系統</title>
		{% include 'main/snippets/css.html' %}
</head>

<body>
<div class='container' style="font-family: 'Noto Sans CJK TC Regular', sans-serif;">
	{% include 'main/snippets/nav.html' %}

	{% block content %}

	{% endblock content %}
</div>
{% include 'main/snippets/js.html' %}
<script>
$(function () {
        $("[data-toggle='tooltip']").tooltip();
    });
</script>
</body>
</html>

main/templates/main/detail.html
{% extends "main/base.html" %}

{% block content %}
<h2>{{ book.book_title }}</h2>

	作者: {{book.book_author}}<br>
	出版時間: {{book.book_pubtime}}<br>
	 {% if book.book_isbn=='1' %}
	 	無
	 {% else %}
	 	{{book.book_isbn}}
	 {% endif %}
	 <br>


{% if book.book_borrowid %}
	借出狀況: {{book.book_borrowid}}
{% else %}
	借出狀況: 未借出
{% endif %}
{% endblock content %}

main/templates/main/history.html
{% extends 'main/base.html'%}
{% block content %}

{% if borrow_list %}
<table class="table" style="width:100%">
	<tr>
		<th>書名</th>
		<th>作者</th>
		<th>出版日期</th>
		<th>ISBN</th>
		<th>借閱日期</th>
		<th>歸還日期</th>
	</tr>
	{% for history in borrow_list %}
		{% if history.return_time == None %}
		<tr>
			<td><font color="green">{{history.title}}</td>
			<td><font color="green">{{history.author}}</td>
			<td><font color="green">{{history.pubtime}}</td>
			<td><font color="green">{{history.isbn}}</td>
			<td><font color="green">{{history.rent_time}}</td>
		</tr>
		{% else %}
		<tr>
			<td>{{history.title}}</td>
			<td>{{history.author}}</td>
			<td>{{history.pubtime}}</td>
			<td>{{history.isbn}}</td>
			<td>{{history.rent_time}}</td>
			<td>{{history.return_time}}

			</td>
		</tr>
		{% endif %}
		{% endfor %}

</table>
{% endif %}
{% endblock content %}

main/templates/main/index.html
{% extends 'main/base.html'%}
{% block content %}
{% if all_book_list %}
<table class="table" style="width:100%;text-align:center">
	<tr>
		<th>書名</th>
		<th>作者</th>
		<th>出版日期</th>
		<th>ISBN</th>
	</tr>
	{% for book in all_book_list %}
		{% if book.book_borrowid %}
		<tr data-toggle="tooltip" title="借閱人：{{book.book_borrowid}} {{ book.book_borrowname }}">
			<td><font color="green">{{book.book_title}}</font></td>
			<td><font color="green">{{book.book_author}}</font></td>
			<td><font color="green">{{book.book_pubtime}}</font></td>
			{% if book.book_isbn == '1' %}
				<td><font color="green">無</font></td>
			{% else %}
				<td><font color="green">{{book.book_isbn}}</font></td>
			{% endif %}
		</tr>

		{% else %}
		<tr>
			<td>{{book.book_title}}</td>
			<td>{{book.book_author}}</td>
			<td>{{book.book_pubtime}}</td>
			{% if book.book_isbn == '1' %}
				<td>無</td>
			{% else %}
				<td>{{book.book_isbn}}</td>
			{% endif %}
		</tr>
		{% endif %}
		{% endfor %}

</table>
{% endif %}
{% endblock content %}

main/templates/main/login.html
{% extends 'main/base.html'%}
{% block content %}
<h2>登入</h2>
	{% if messages %}
	{% for message in messages %}
	  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
	    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	      <span aria-hidden="true">&times;</span>
	    </button>
	    {{ message }}
	  </div>
		{% endfor %}
		{% endif %}
	<form method="post">
		{% csrf_token %}
		{% for field in form %}
		<p>
			<div class="fieldWrapper">
					{{ field.errors }}
					{{ field.label_tag }}<br>
					{{ field }}
			</div>
		</p>
	{% endfor %}
	<input type="submit" class="btn btn-primary" value="登入">
</form>
{% endblock content %}

main/templates/main/name.html
{% extends 'main/base.html'%}
{% block content %}
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock content %}

main/templates/main/register.html
{% extends 'main/base.html' %}

{% block content %}
  <h2>註冊</h2>
  <form method="post">
  		{% for field in form %}
  		{% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% endfor %}
		{% csrf_token %}
		<p>
			<label for="id_username">使用者名稱：</label><br>
				<input type="text" name="username" id="id_username" required maxlength="150" />
				<small style="color: grey">必要的。150 個字或更少，只包含字母、數字和 @/./+/-/_。</small>
		</p>
		<p>
			<label for="id_real_name">真實姓名：</label><br>
				<input type="text" name="real_name" id="id_real_name" required maxlength="5" />
				<small style="color: grey">例如：李杰穎</small>
		</p>
		<p>
			<label for="id_school_id">學號：</label><br>
			<input type="text" name="school_id" id="id_school_id" required maxlength="5" />
				<small style="color: grey">例如：41402</small>
		</p>
		<p>
			<label for="id_password1">密碼：</label><br>
			<input type="password" name="password1" id="id_password1" required />
				<small style="color: grey">密碼不能與其他個人資訊太相近。必須包含至少 8 個字元。不能使用常見的密碼。密碼不能完全是數字。</small>
		</p>
		<p>
			<label for="id_password2">密碼確認：</label><br>
			<input type="password" name="password2" id="id_password2" required />
				<small style="color: grey">為檢查用，請輸入與前面相同的密碼。</small>
		</p>

		<button class="btn btn-primary" type="submit">註冊</button>
</form>
{% endblock %}

main/templates/main/rent.html
{% extends 'main/base.html'%}
{% block content %}
<!-- 目前構想
isbn 欄位(每個人都不會亂借書)
登錄後自動填入班級座號姓名
設計可借閱多本書的類似表格的系統
自動判斷借閱或歸還
	 	-->
<!-- 刷入書籍 書籍isbn 出版日期 作者  -->
{% if messages %}
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
{% endif %}
<table class="table-hover" style="width:100%">
	<tr>
		<th>書名</th>
		<th>作者</th>
		<th>出版日期</th>
		<th>ISBN</th>
	</tr>
	{% for book in book_list %}
		{% if book.book_borrowid == user.profile.school_id %}
		<tr>
			<td><font color="green">{{book.book_title}}</font></td>
			<td><font color="green">{{book.book_author}}</font></td>
			<td><font color="green">{{book.book_pubtime}}</font></td>
			<td><font color="green">{{book.book_isbn}}</font></td>
		</tr>
		{% else %}
		<tr>
			<td>{{book.book_title}}</td>
			<td>{{book.book_author}}</td>
			<td>{{book.book_pubtime}}</td>
			<td>{{book.book_isbn}}</td>
		</tr>
		{% endif %}
	{% endfor %}

</table>
<br>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="送出" />
</form>
{% if book_list|length >= 1 %}
<input type="button" value='確認借閱&amp歸還' onclick="location.href='/book/rent/confirm'" class="btn btn-primary">
{% endif %}
<script>
	var input = document.getElementById("id_book_barcode");
	input.focus();
</script>
{% endblock content %}

main/templates/main/rent_confirm.html
{% extends 'main/base.html' %}
{% block content %}
{% if messages %}
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
{% endif %}

{% if borrow_list|length >= 1 %}
借閱&amp;歸還書籍如下：
<table class="table-hover" style="width:100%">
	<tr>
		<th>書名</th>
		<th>作者</th>
		<th>出版日期</th>
		<th>ISBN</th>
	</tr>
	{% for book in borrow_list %}
	{% if book.book_borrowid == user.profile.school_id %}
	<tr>
		<td><font color="green">{{book.book_title}}</font></td>
		<td><font color="green">{{book.book_author}}</font></td>
		<td><font color="green">{{book.book_pubtime}}</font></td>
		<td><font color="green">{{book.book_isbn}}</font></td>
	</tr>
	{% else %}
	<tr>
		<td>{{book.book_title}}</td>
		<td>{{book.book_author}}</td>
		<td>{{book.book_pubtime}}</td>
		<td>{{book.book_isbn}}</td>
	</tr>
	{% endif %}
	{% endfor %}
</table>

{% endif %}
{% endblock content %}